# themes from https://github.com/alacritty/alacritty-theme

# import = ["/Users/mischa/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["~/.config/alacritty/themes/themes/gnome_terminal.toml"]

[font]
size = 16

[font.normal]
family = "MesloLGS NF"

[window]
option_as_alt = "OnlyLeft"

[window.padding]
x = 7
y = 0
